catch не выполнится, потому что перед ним есть обработчик throw new Error